=== leoyodar/Grupo-3---UNIR/Lenguajes, Estandares y Tecnologias para la Web/Schemas/Alan schemas/todolist.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="todolist">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="todo" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="description" type="xs:string"/>
              <xs:element name="datecreated" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name="value" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="status">
                <xs:complexType>
                  <xs:attribute name="type">
                    <xs:simpleType>
                      <xs:restriction base="xs:string">
                        <xs:enumeration value="done"/>
                        <xs:enumeration value="todo"/>
                        <xs:enumeration value="doing"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
              <xs:element name="duedate" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name="value" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="todoauthor">
                <xs:complexType>
                  <xs:attribute name="author" type="xs:IDREF" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="author" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="imagen">
                <xs:complexType>
                  <xs:attribute name="src" type="xs:anyURI" use="required"/>
                  <xs:attribute name="alt" type="xs:string" use="optional"/>
                  <xs:attribute name="width" type="xs:string" use="optional"/>
                  <xs:attribute name="height" type="xs:string" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== leoyodar/Grupo-3---UNIR/Lenguajes, Estandares y Tecnologias para la Web/Schemas/Alan schemas/todolist.xml
<?xml version="1.0" encoding="UTF-8" ?>
<todolist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="todolist.xsd" >
    <todo id="t-1">
        <name>Revisar correos</name>
        <description>Antes de cualquier actividad debo leer mis correos</description>
        <datecreated value="10-12-2023"/>
        <status type="doing"/>
        <duedate value="05-03-2022"/>
        <todoauthor author="a-1"/>
    </todo>
    <todo id="t-2">
        <name>Enviar correos</name>
        <description>Enviar correos de con la informaci√≥n de la reunion</description>
        <datecreated value="03-23-2023"/>
        <status type="todo"/>
        <todoauthor author="a-1"/>
    </todo>
    <author id="a-1">
        <name>Ana Doe</name>
        <imagen src="./recursos/picture-1.jpeg"/>
    </author>
    <author id="a-2">
        <name>John Doe</name>
        <imagen src="./recursos/picture-2.webp"/>
    </author>
</todolist>
